### ISSUE TITLE
3D view upside-down?

### ISSUE THREAD

**Issue by ianni67** [adujardin/zed-openpose#12]
Perhaps I'm missing something very simple, but this issue is making me scratch my head.
Zed-openpose is showing me the 3D view upside-down and every time I start it I have to manually rotate the view. What am I missing?
Thank you in advance for your help

**Comment by adujardin** [comment]
Yes, this is actually "normal". I never took the time to fix the default camera viewport. I think it should be changed [here](https://github.com/adujardin/zed-openpose/blob/master/src/GLViewer.cpp#L656)

**Comment by ArghyaChatterjee** [comment]
Hello, @ianni67 , have you fixed the issue? I am also facing the same problem. Any update will be helpful. TIA.

**Comment by ianni67** [comment]
> Hello, @ianni67 , have you fixed the issue? I am also facing the same problem. Any update will be helpful. TIA.

I did not, unfortunately. I'm working on a "headless" version of zed-openpose that saves the joints data on a file, so I do not care to visualize the data in real-time. As a consequence, I stripped the visualization part away.

**Comment by ArghyaChatterjee** [comment]
Actually I figured it out just now @ianni67. I actually modified the line according to the suggestion of @adujardin. Just changed line no. 656 of GLViewer.cpp file inside /zed-openpose/src directory. I replaced line 656 ```sl::float3 euler(180, 0, 0);``` with ```sl::float3 euler(0, 0, 0);```. You can see the output video made & published by me on my youtube channel: https://www.youtube.com/watch?v=p4c1ApCcQb8.
Also I had to initially change some parameters in the cmakelists.txt file during building the zed-openpose directory in order to get Openpose up & running with ZED. 
I am running Ubuntu 18.04 LTS with Nvidia driver 440.33, CUDA 10.2, Cudnn 7.6.5 & OpenCV 3.4.8 on Core i7-8 core Intel Processor, 24 Gb RAM & Nvidia 1070M Graphics.
